name: weather_riverpod
description: "Weather template app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management & DI
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Networking
  dio: ^5.3.4
  retrofit: ^4.0.3

  # Routing
  go_router: ^12.1.1

  # Immutable Data Structures
  freezed: ^2.4.5

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Annotation
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Test
  mockito: ^5.4.3

dev_dependencies:
  # Core
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Serialization
  json_serializable: ^6.7.1

  # Code Generation
  riverpod_generator:
  retrofit_generator:
  envied_generator:
  build_runner:

  # Logging
  logger:

  # Native UI
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/common/l10n
  output_dir: lib/common/l10n/generated
