name: weather_riverpod
description: "Weather template app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management & DI
  riverpod: ^2.4.8
  flutter_riverpod: ^2.4.8

  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3

  # Immutable Data Structures
  freezed: ^2.4.5

  # Localization
  easy_localization: ^3.0.3

  # Annotation
  riverpod_annotation: ^2.3.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Test
  mockito: ^5.4.3

dev_dependencies:
  # Core
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Serialization
  json_serializable: ^6.7.1

  # Code Generation
  riverpod_generator:
  retrofit_generator:
  envied_generator:
  build_runner:

  # Logging
  logger:

  # Native UI
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6


flutter:
  uses-material-design: true
